# Generated by Django 5.2.6 on 2026-05-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
