# Generated by Django 5.2.6 on 2026-05-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='pending_final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
