# Generated by Django 5.2.6 on 2026-05-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0002_negotiation_pending_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='project_status',
            field=models.CharField(choices=[('negotiating', 'Negotiating'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='negotiating', max_length=20),
        ),
        migrations.AddField(
            model_name='negotiationmessage',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='negotiationmessage',
            name='message_type',
            field=models.CharField(choices=[('negotiation', 'Negotiation Message'), ('chat', 'Chat Message'), ('milestone', 'Milestone Update'), ('progress', 'Progress Update')], default='negotiation', max_length=20),
        ),
        migrations.AddField(
            model_name='negotiationmessage',
            name='milestone_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negotiationmessage',
            name='progress_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
