# Generated by Django 5.2.6 on 2026-05-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0003_negotiation_progress_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationmessage',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
