# Generated by Django 5.2.6 on 2026-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='status',
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
