# Generated by Django 5.2.6 on 2026-06-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanapplication',
            name='skill_category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('painting', 'Painting'), ('cleaning', 'Cleaning'), ('carpentry', 'Carpentry'), ('other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
