# Generated by Django 5.2.6 on 2026-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapplication', '0002_artisanapplication_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanapplication',
            name='skill_category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('mechanic', 'Mechanic'), ('painting', 'Painting'), ('cleaning', 'Cleaning'), ('carpentry', 'Carpentry'), ('other', 'Other')], max_length=50),
        ),
    ]
