# Generated by Django 5.2.6 on 2026-05-28 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_jobrequest_latitude_jobrequest_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_5_star', models.IntegerField(default=0)),
                ('total_4_star', models.IntegerField(default=0)),
                ('total_3_star', models.IntegerField(default=0)),
                ('total_2_star', models.IntegerField(default=0)),
                ('total_1_star', models.IntegerField(default=0)),
                ('worker_completion_rate', models.FloatField(default=0)),
                ('client_reliability_rate', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_summary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('client_to_worker', 'Client to Worker'), ('worker_to_client', 'Worker to Client')], max_length=20)),
                ('rating', models.IntegerField(choices=[(1, '⭐ - Poor'), (2, '⭐⭐ - Fair'), (3, '⭐⭐⭐ - Good'), (4, '⭐⭐⭐⭐ - Very Good'), (5, '⭐⭐⭐⭐⭐ - Excellent')])),
                ('comment', models.TextField()),
                ('communication_rating', models.IntegerField(blank=True, choices=[(1, '⭐ - Poor'), (2, '⭐⭐ - Fair'), (3, '⭐⭐⭐ - Good'), (4, '⭐⭐⭐⭐ - Very Good'), (5, '⭐⭐⭐⭐⭐ - Excellent')], null=True)),
                ('quality_rating', models.IntegerField(blank=True, choices=[(1, '⭐ - Poor'), (2, '⭐⭐ - Fair'), (3, '⭐⭐⭐ - Good'), (4, '⭐⭐⭐⭐ - Very Good'), (5, '⭐⭐⭐⭐⭐ - Excellent')], null=True)),
                ('punctuality_rating', models.IntegerField(blank=True, choices=[(1, '⭐ - Poor'), (2, '⭐⭐ - Fair'), (3, '⭐⭐⭐ - Good'), (4, '⭐⭐⭐⭐ - Very Good'), (5, '⭐⭐⭐⭐⭐ - Excellent')], null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobs.jobrequest')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job', 'reviewer', 'review_type')},
            },
        ),
    ]
