# Generated by Django 5.2.6 on 2026-05-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.CharField(blank=True, choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('mechanic', 'Mechanic'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('cleaner', 'Cleaner'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
