# Generated by Django 5.2.6 on 2026-05-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.CharField(blank=True, choices=[('plumbing', 'Plumbing'), ('mechanic', 'Mechanic'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('painting', 'Painting'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
